server:
  port: 8081

spring:
  application:
    name: auth-service-stub

logging:
  level:
    root: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

auth:
  issuer: auth-service-stub
  key-id: local-demo-rsa
  token-ttl: PT1H
  # Clave privada RSA-2048 de pruebas. Reemplazar por AWS Secrets Manager / IdP real fuera del MVP.
  private-key: ${AUTH_JWT_PRIVATE_KEY:MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDgLeuRubeVU6Z1MUkf98ZM3PUWT5Jwki75KQVcl27wP0LXRf0GamP3ujCR+BfbMZtn6MONu/AIgOQgrFbUrOB14bERZKdhQEIfl9qSpbV/p4DUHTzKhZPVbMAHjoIjoOW70V33rn/M3W1bPMWum+auapkOmbl9WwLGwNKtGsqE7frAwlWlcwXFE3GZghtCbD8KwoIDigl1NoLTAoXzqzmneyd6qzi0f95M2GPKtum59iRLpoNY7FLG2qFfkLUJGoX7rlCgvK9GVOhwuzr075dFCgNjFrm15kzvuy2YsyoCNkK0NWlKc1piSexqpCdL0B8+JgAond132qX+NgXlS0X1AgMBAAECggEAKdTHwUB7XjTmubWBpKJycUNFxG0CsVjFxR5/bqCfRds4GL1pknnlv4MRrxsxMGiYTBJl8xuflaafau1don/DvptnlAxJI19/Ny/5zCV5saFK68ms30l/pXKOfpp79DQAykQuGZqJJGwpDL5RUNysdd1URCIxN4/0+6tdZIm8QoNgPlqTh8RJ3I3HkIvHrvBrsPmFxgXiCqTBWQaJnOIKYCG4rSi3M1pnV67L7yKYwKCoJd8zsiCHfF7w9Yc0pI6F/y4MLgr8zdmKcacvbID6IhghuVT8hvHUAxb2fccJNU1tGJqegAXB2jYpb7XX/lGtK/BDXrjUH9U5WQ0Bk6Pn3QKBgQDsVtTlDQs5ZePCmdLd19T2495YHM9zNRP4CijcnsA1/1vf7TlZ80j7GHeoGUbrXYXtl6okZoKZIhrS+8fXlrvGvYzNUvJwtGnFgauqgbqIGFMueFa9PUJh6QsP24/feFG3x+wmJ4gC30G1NqPtdWbaEY8EYuyscvJkNbSbwXykjwKBgQDy1CDwg89zF573JqKcq9btsEEy7uvSbJ+kmcBhhRK4arifuncd89yV1M/bqRg9w9fMjrIAgejoCPi36v4uEWarXJwSsuWhC9R62hfEyojtiFCtqATXMIQJZyF19aCUnc74814m7NIj3mMYyfcQJ6Q1q5YZCb5yIWlvmgZk6e+XOwKBgQCFeAglDre/A4abuKk4NZKEl21Sz3pscpZDZuFqrpCYLg0hqePQo68cdtXkbdn6Q8fFxPgGNIoelv8VFbHnU63Z7+QbdHOMKKbvLmrXEQpZn3sibD14A6eAic6AdxuKNXXY1yPK7FpIXPLLtv7etIWQM4hUDtXgEc5Hv3iu2ZddiwKBgQCLMKkI9KUu9bU7OjwvzhhO+p8E0Qr//R+tPCyYOa03ZIUbmci5tJUWlXvoD49DqETEjm7d95lHmAzpb5vvUC4nv9f+p+kUXTGYkfbZ6LaAYYjNYegUaUzmDuWRNhCr36FJ9kZbzZfO06S+CtbBvddUpFxPUdSGmzxSqllL8wRRDQKBgQCank0aJV4aiA51IenK69O03w1+HVYRV6SrFmhjoQf5JmSgd6uneunbLsgd76+VRyoQP9bsWgHyPauQSuk1lKstyou1YsD1k2uiE92TDuoGcRcfvR/fJJggpvCRxChth7ad6qRne1YWEqxMZ9VRpOkgVlZwwcS/QD+8+VGjCGen1w==}
  users:
    - id: "11111111-1111-1111-1111-111111111111"
      nombre: "Laura Participante"
      email: "laura.participante@javeriana.edu.co"
      password: "demo123"
      roles: ["PARTICIPANTE"]
    - id: "22222222-2222-2222-2222-222222222222"
      nombre: "Diego Participante"
      email: "diego.participante@javeriana.edu.co"
      password: "demo123"
      roles: ["PARTICIPANTE"]
    - id: "33333333-3333-3333-3333-333333333333"
      nombre: "Carlos Organizador"
      email: "carlos.organizador@javeriana.edu.co"
      password: "demo123"
      roles: ["ORGANIZADOR"]
    - id: "44444444-4444-4444-4444-444444444444"
      nombre: "Ana Administradora"
      email: "ana.admin@javeriana.edu.co"
      password: "demo123"
      roles: ["ADMIN"]
    - id: "55555555-5555-5555-5555-555555555555"
      nombre: "Sofia Mesa de Ayuda"
      email: "sofia.soporte@javeriana.edu.co"
      password: "demo123"
      roles: ["PARTICIPANTE"]
